# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 675aa5faf573ca946a89901af6ade02ce46a28489f2514c714a29c13fe309318080a4bd46a2c8d27f3f99601e7ae872ee8b13b985bf227cf5a0af2ddac212041

test:
  secret_key_base: 2f2ae0d3906b1ca231658110a191141ec82c88ad975e611672f474127f19e42c2addccf4292836dd4b7c48a1302a07d74e6b29e8e9a304ed771b52ce8e9d5ead

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
